### ISSUE TITLE
Fast-key erasure RNG using AES-NI

### ISSUE THREAD

**Issue by vks** [RustCrypto/stream-ciphers#1]
I ported [jedisct1/aes-stream](https://github.com/jedisct1/aes-stream) to Rust: [vks/aesrng](https://github.com/vks/aesrng). Would this be of interest to this repository?

**Comment by newpavlov** [comment]
Not in this repo, but it can be a good addition to [CSRNGs](https://github.com/RustCrypto/CSRNGs) repo. BTW it will be nice if you'll implement traits from `rand_core` crate.

**Comment by newpavlov** [comment]
Also can you provide any specifications of the implemented algorithm? We would like to avoid inclusion of home brew algorithms.

@tarcieri 
What do you think?

**Comment by vks** [comment]
> it will be nice if you'll implement traits from rand_core crate.

Already done on my local branch, I just need to update it to use the recently published crate.

> Also can you provide any specifications of the implemented algorithm?

The algorithm was suggested on [djb's blog](https://blog.cr.yp.to/20170723-random.html). I think it is implemented for various ciphers in SUPERCOP (see `fastrandombytes`). This gives it some legitimacy, but IMHO it still has to be considered homebrewn.

> Can this algorithm be written generically over block cipher, so you could use aesni crate, without losing performance?

Maybe, but it is currently written using very low-level SIMD, so it is probably a lot of work to do this.

**Comment by tarcieri** [comment]
@newpavlov it's an interesting algorithm that provides a nicely fast CSPRNG wherever hardware AES is available. I'd be in favor of including it

**Comment by newpavlov** [comment]
@vks 
Can you please create a PR to [CSRNGs](https://github.com/RustCrypto/CSRNGs) repository?

**Comment by vks** [comment]
I will look into it, but not before August 13.

**Comment by vks** [comment]
Closed in favor of https://github.com/RustCrypto/CSRNGs/issues/2.
