### ISSUE TITLE
Can the salsa20 family be pushed to crates.io?

### ISSUE THREAD

**Issue by sseemayer** [RustCrypto/stream-ciphers#15]
Similar to #2, I am migrating away from `rust-crypto` and would like to use the Salsa20 and ChaCha20 implementations contained in `stream-ciphers`. Would it be possible to push them to crates.io?

**Comment by tarcieri** [comment]
I think it's ok to publish as is, although I think it'd be nice to find some way to factor it into `salsa20` and `chacha20` crates.

**Comment by sseemayer** [comment]
I would be willing to give that refactoring a stab if given some guidance on what is desired. 

Salsa20 and ChaCha20 share `SalsaFamilyState` and `SalsaFamilyCipher`. Do you suggest to have this struct and trait in a `salsa20-family` crate that will be re-exported from a `salsa20` and `chacha20` crate?

**Comment by tarcieri** [comment]
That's one possible approach, yes

**Comment by newpavlov** [comment]
I've registered `salsa20-core` crate, which we can use for common functionality.

@tarcieri 
Now you should have access to `salsa20-core`, `salsa20` and `chacha20` crates, so you can upload crates yourself.

**Comment by tarcieri** [comment]
@newpavlov excellent, thanks

**Comment by sseemayer** [comment]
Wow, that's a quick response. Would you like me to submit a PR or do this refactoring yourselves?

**Comment by newpavlov** [comment]
I think it will be faster for you to create a PR. Also we always welcome new contributors. :)

**Comment by sseemayer** [comment]
Great, I'll get right to it!

**Comment by sseemayer** [comment]
Would you like to keep the `salsa20-family` crate as a meta-crate that bundles `salsa20` and `chacha20` crates?

**Comment by tarcieri** [comment]
Probably not. It's just a name we picked in the course of the PR.

**Comment by newpavlov** [comment]
I don't think we need a meta-crate, in my experience they are rarely used in practice. So lets use only 3 crates. BTW while you at it, please update table in README with the added crates.

**Comment by sseemayer** [comment]
OK, I think the PR #16  is ready for review now.

**Comment by tarcieri** [comment]
Now that #16 is merged, I have published (and pushed tags for) the following releases:

- [`chacha20` v0.1.0](https://crates.io/crates/chacha20/0.1.0)
- [`salsa20` v0.1.0](https://crates.io/crates/salsa20/0.1.0)
- [`salsa20-core` v0.1.0](https://crates.io/crates/salsa20-core/0.1.0)
