### ISSUE TITLE
released cfb-mode depends on block-cipher@0.7

### ISSUE THREAD

**Issue by dignifiedquire** [RustCrypto/stream-ciphers#163]
But most other crates now depend on block-cipher@0.8 making it impossible to upgrade for me

**Comment by newpavlov** [comment]
I was trying to merge RustCrypto/traits#260 and release crates dependent on `stream-cipher v0.7`, but I got sidetracked. If no progress will be made on that PR, I will release the existing versions in a day or two.

**Comment by dignifiedquire** [comment]
thanks

**Comment by newpavlov** [comment]
`cfb-mode` v0.5.0 is released!
