### ISSUE TITLE
chacha20/salsa20/salsa20-core: Improve README.md

### ISSUE THREAD

**Issue by tarcieri** [RustCrypto/stream-ciphers#17]
Each of these crates could use a README.md with some basic information, and the following added to their Cargo.toml files:

```toml
readme = "README.md"
```

Right now they look pretty bare on crates.io, e.g.:

https://crates.io/crates/chacha20

**Comment by newpavlov** [comment]
Well, most crates in this org do not have per-crate READMEs right now. I think improving in-crate documentation should have a higher priority, as right now it's essentially non-existent for those crates.

Of course eventually it's worth to add READMEs as well, hopefully for all user-facing crates.

**Comment by tarcieri** [comment]
I think crate-specific READMEs are important because it aids in discoverability through crates.io
