### ISSUE TITLE
request for rabbit cipher

### ISSUE THREAD

**Issue by lzy1g1225** [RustCrypto/stream-ciphers#171]
Hi, can you add the rabbit encryption method? I am using rabbit in my c++ project using cryptopp, the reason is it is said rabbit is the fastest stream cipher. Thank you for awesome job!

**Comment by tarcieri** [comment]
It looks like there's one available here, however it hasn't been touched in 5 years:

https://crates.io/crates/rabbit

Perhaps we can try to get in touch with the author and see if they're interested in upstreaming it to this project.
