### ISSUE TITLE
ctr: block size vs counter size naming

### ISSUE THREAD

**Issue by tarcieri** [RustCrypto/stream-ciphers#172]
There's an open PR to add support for CTR mode with a 128-bit block size and 32-bit counter: #170.

This PR uses the name `Ctr32` but this does not reflect the hardcoded 128-bit block size.

Additionally #75 adds support for natively 128-bit counters, versus the 64-bit counter currently used by the `Ctr128` type.

How should we handle these discrepancies? Some suggestions:

1. Make all implementations completely generic over  the block size
2. Introduce some way of incorporating the hardcoded block size into the name, e.g. `Ctr128x32`
3. Give up on incorporating the block size into the name and say all implementations assume a 128-bit block size

**Comment by tarcieri** [comment]
Note: in #170 I was able to use the first approach and make `Ctr32BE` and `Ctr32LE` generic over block sizes.

**Comment by newpavlov** [comment]
I think this issue has been addressed in #195 by introducing `seek_block` and `current_block` methods. So we probably can close it? Ideally those methods would be exposed in a `cipher` trait, but it's blocked on designing a block-level API for stream ciphers.

**Comment by tarcieri** [comment]
So yes, I consider this issue addressed, but the reason is:

- `Ctr128` now has a 128-bit counter instead of a 64-bit one
- There are now `Ctr32` and `Ctr64` with 32-bit/64-bit counters respectively

All of them are still hardcoded to `BlockCipher<BlockSize = U16>`, but as long as there's a way to distinguish the counter sizes easily I'm happy.
