### ISSUE TITLE
Publish on crates.io?

### ISSUE THREAD

**Issue by mersinvald** [RustCrypto/stream-ciphers#2]
Hello, we're currently migrating from rust-crypto crate because of wasm-build related problems (see issue https://github.com/ETCDEVTeam/emerald-rs/issues/286) and the decomposition you've done looks very promising in terms of integration into wasm-capable project.

What's the current state of stream-ciphers and when do you expect it to be possible to post it on crates.io?

**Comment by tarcieri** [comment]
It's something I've been meaning to work on soon (I need it for both [Miscreant](https://github.com/miscreant/miscreant) and the basis of a ChaCha20 implementation). That said if @newpavlov beats me to it, that'd be fine by me.

**Comment by mersinvald** [comment]
@tarcieri okay, thank you, that's good news. Will check the Miscreant too :)

**Comment by newpavlov** [comment]
In this or next week I plan to publish AES-CTR (probably on this weekend), which if understand correctly is the last thing `emerald-rs` needs to migrate from `rust-crypto`.

**Comment by mersinvald** [comment]
@newpavlov yep, that's correct.

**Comment by newpavlov** [comment]
I've published `aes-ctr v0.1.0`. Feel free to ask here if you'll have any difficulties with it!
