### ISSUE TITLE
Remove circular dependencies on `aes` crate

### ISSUE THREAD

**Issue by tarcieri** [RustCrypto/stream-ciphers#237]
Several crates in this repo use the `aes` crate as a dev-dependency.

The `aes` crate lists `ctr` in its (hard) `dependencies` section now.

This means that upgrading the `cipher` crate right now involves at least a temporary breakage. Here are some example PRs where this has happened:

#224 #225 #226 #227

There are at least two different ways this could be addressed, I think:

1) Migrate the SIMD CTR implementation from the `aes` crate into the `ctr` crate, since it's not `ctr`-specific
2) Use a different "example" block cipher as a `dev-dependency`

**Comment by newpavlov** [comment]
I think a better approach would be to move all block mode crates to the block ciphers repository, as attempted in the RustCrypto/block-ciphers#233.
