### ISSUE TITLE
Poly1305

### ISSUE THREAD

**Issue by tarcieri** [RustCrypto/stream-ciphers#29]
Seems like we have fairly reasonable ChaCha20 crates and Salsa20 crates now, and I see newpavlov snagged https://crates.io/crates/poly1305

A `poly1305` crate seems like the next logical step, but where should it go? Right now I think the closest fit is https://github.com/RustCrypto/hashes but that seems a little weird

Should we stick it under `hashes`, or do we need a new toplevel project like `universal-hashes` or `one-time-authenticators`?

As it were, I have a mostly complete (but completely untested) Rust implementation of POLYVAL that needs a home and could be located in the same place: https://github.com/miscreant/miscreant.rs/blob/047ae8b3fd68d62eeb1e8510110439ba24473df3/src/polyval.rs

**Comment by newpavlov** [comment]
Shouldn't it go to the RustCrypto/MACs repo? It's already listed in RustCrypto/MACs#1.

**Comment by tarcieri** [comment]
@newpavlov I guess that works, except Poly1305 in and of itself is not a MAC... to be used as a MAC in and of itself it needs to be paired with a cipher ala Poly1305-AES (ditto for POLYVAL/GHASH vs GMAC)

**Comment by newpavlov** [comment]
Can't we implement `Mac` trait only for a structure generic over `StreamCipher`/`BlockCipher`? I don't have exact API in mind, but I think it should be doable.

**Comment by tarcieri** [comment]
@newpavlov sure, that sounds good.

**Comment by tarcieri** [comment]
PR to add Poly1305 to `RustCrypto/MACs` here: https://github.com/RustCrypto/MACs/pull/12
