### ISSUE TITLE
Locking `zeroize` to `<=1.5` for `chacha` prevents compiling with `num-bigint-dig v0.8.1` (for `rsa 0.6.0-pre`)

### ISSUE THREAD

**Issue by poliorcetics** [RustCrypto/stream-ciphers#296]
Maybe we could have a feature to ignore MSRV, that is not activated by default

**Comment by tarcieri** [comment]
See the master tracking issue here: https://github.com/RustCrypto/utils/issues/723

**Comment by tarcieri** [comment]
The latest release does not have this restriction

**Comment by poliorcetics** [comment]
Thanks a lot !
