### ISSUE TITLE
version 0.9.0 does not compile on Arduino architecture

### ISSUE THREAD

**Issue by mutantbob** [RustCrypto/stream-ciphers#297]
Rust support for arduino is lagging and at the moment a number of bugs in the toolchain prevent the use of any rust newer than nightly-2021-01-07.

When I try to build I get the following error:

```
error: failed to download `inout v0.1.2`

Caused by:
  unable to get packages from source

Caused by:
  failed to parse manifest at `/home/thoth/.cargo/registry/src/github.com-1ecc6299db9ec823/inout-0.1.2/Cargo.toml`

Caused by:
  failed to parse the `edition` key

Caused by:
  this version of Cargo is older than the `2021` edition, and only supports `2015` and `2018` editions.
```

There are a number of solutions, most of which are out of your hands:

- use chacha20 version 0.8.1
- stop using inout or put it behind a feature flag
- change inout to not use edition 2021
- fix the various bugs modern in Rust that prevent it from correctly generating code for the Arduino

**Comment by tarcieri** [comment]
We're generally moving to the 2021 edition across all of our crates, which is a fairly common thing across the Rust ecosystem.

I would suggest you use the older releases of these crates which support an older MSRV until the Arduino compiler updates.
