### ISSUE TITLE
Add more warnings to crate docs

### ISSUE THREAD

**Issue by rvolgers** [RustCrypto/stream-ciphers#3]
I have a couple of suggestions that might help people understand the security properties of this library, even if they don't know much about crypto.

* The subcrates are published on crates.io, but the subcrates don't include the warning of the top-level crate that there has been no formal security review.
* There is no mention of a common mistake made with stream ciphers: if you reuse the same keystream state to encrypt two different things it almost certainly gives an attacker enough information to break whatever security properties the cryptography is supposed to preserve. If an attacker only has the two ciphertexts they can determine the precise XOR difference between the corresponding plaintexts, and if the attacker knows (or can guess) part of one of the plaintexts they can recover that part of the other message's plaintext.
* Related to the previous point, there should probably be an explicit link pointing people towards  higher level cryptographic functionality that avoids such gotchas.

**Comment by newpavlov** [comment]
I think that general information about stream ciphers are be better provided as part of the `stream-cipher` crate, while implementation crates will just reference it with an appropriate message instead of duplicating explanations each time.

**Comment by tarcieri** [comment]
All of these crates now have a "hazmat" warning explaining some of the pitfalls.

I think it could be further expanded (e.g. more specific warnings about nonce reuse), and some of it consolidated in the `stream-cipher` crate as @newpavlov suggested, but I think the new warnings address the primary scope of these complaints.
