### ISSUE TITLE
Publish `chacha20` crate which is available `neon` feature

### ISSUE THREAD

**Issue by sorairolake** [RustCrypto/stream-ciphers#312]
They want to use this feature in [`shadowsocks-crypto`](https://crates.io/crates/shadowsocks-crypto) crate, but this is not yet available. When will this feature available version be published?

see also: shadowsocks/shadowsocks-crypto#19

**Comment by tarcieri** [comment]
The unaddressed (potential) work item is gating the feature on a `cfg!` attribute instead of a crate feature, like we have moved to in most other crates.

This prevents transitive dependencies from activating the feature and ensures it's controlled completely by the toplevel binary.
