### ISSUE TITLE
Make the neon feature available for ChaCha20

### ISSUE THREAD

**Issue by skerkour-dev** [RustCrypto/stream-ciphers#316]
Hello,

Today ChaCha20 (and by extension `(X)ChaCha20-Poly1305`) is painfully slow on arm64 devices.

NEON support was merged last year (https://github.com/RustCrypto/stream-ciphers/pull/310) but is still not available for use.

Is it possible to publish a new version and update the docs so we can use the NEON version?

I can create a PR for the doc (adding a few explanation on how to enable NEON support) if necessary.

Many thanks!

**Comment by tarcieri** [comment]
As noted on #310, the reason it hasn't been released yet is that the PR gated it under a feature and we would like to move it to a `cfg` attribute for consistency with other crates like `aes`

**Comment by tarcieri** [comment]
I opened #317 to add the `cfg` attribute

**Comment by skerkour-dev** [comment]
Many thanks 🙏
