### ISSUE TITLE
ChaCha20 multithreading

### ISSUE THREAD

**Issue by FU3X** [RustCrypto/stream-ciphers#340]
How can I process ChaCha20 with multiple threads? I found this:
https://link.springer.com/article/10.1007/s11227-021-04023-9

In my case I want to get a 10 mb chunk of a file, multithread encrypt that 10 mb in parallel repeat. Or is that not a good method? Can someone suggest me an implementation? I just want to encrypt a 5TB file as fast as possible.

**Comment by newpavlov** [comment]
You need to use seeking to achieve it, i.e. inside a worker thread you get chunk number, multiply it by chunk size, seek local copy of cipher to this position, and finally perform encryption.

But note that single instance of ChaCha stream cipher does not allow you to encrypt more than 256 GiB of data because it uses 32-bit block counters. The [legacy variant](https://docs.rs/chacha20/latest/chacha20/type.ChaCha20Legacy.html) uses 64-bit counter, but our implementation currently uses 32-bit counter.

If you still want to encrypt your file with a single cipher, you can use 64-bit [CTR mode](https://docs.rs/ctr) with [AES](https://docs.rs/aes). On most modern CPUs with AES hardware acceleration it can be even faster than ChaCha.

Also, I really hope that you understand all dangers associated with using unauthenticated encryption.

**Comment by tarcieri** [comment]
If you use the [`aead::stream`](https://docs.rs/aead/latest/aead/stream/index.html) construction, particularly in combination with the [`StreamPrimitive`](https://docs.rs/aead/latest/aead/stream/trait.StreamPrimitive.html) trait, you can operate over multiple AEAD segments in parallel.

Unfortunately we don't have any ready-made code for this sort of multithreaded operation, although it would be nice to implement with e.g. `rayon`.

**Comment by FU3X** [comment]
> You need to use seeking to achieve it, i.e. inside a worker thread you get chunk number, multiply it by chunk size, seek local copy of cipher to this position, and finally perform encryption.
> 
> 
> 
> But note that single instance of ChaCha stream cipher does not allow you to encrypt more than 256 GiB of data because it uses 32-bit block counters. The [legacy variant](https://docs.rs/chacha20/latest/chacha20/type.ChaCha20Legacy.html) uses 64-bit counter, but our implementation currently uses 32-bit counter.
> 
> 
> 
> If you still want to encrypt your file with a single cipher, you can use 64-bit [CTR mode](https://docs.rs/ctr) with [AES](https://docs.rs/aes). On most modern CPUs with AES hardware acceleration it can be even faster than ChaCha.
> 
> 
> 
> Also, I am not sure you need multithreading in the first place. Even with SSDs, you likely will be bottlnecked by IO, not CPU.
> 
> 
> 
> Finally, I really hope that you understand all dangers associated with using unauthenticated encryption.
> 
> 

yea, i guess i don't need multithreading, would it be a good idea to use tokio for this though, if im encrypting a mass amount of files

**Comment by newpavlov** [comment]
>would it be a good idea to use tokio for this though

Not if your backend is epoll (tokio uses threadpool to handle disk IO in this case). I think that simply `mmap`ing files and encrypting the mapped memory will give you almost full possible performance. You may need to spawn several threads to keep SSD IO queue full, but you may not need even that, since OS prefetcher should keep them full for large enough files.

**Comment by FU3X** [comment]
> > would it be a good idea to use tokio for this though
> 
> Not if your backend is epoll (tokio uses threadpool to handle disk IO in this case). I think that simply `mmap`ing files and encrypting the mapped memory will give you almost full possible performance. You may squeeze the last drops of performance using io-uring and NVMe commands, but I am not sure the additional complexity is worth the trouble in this case. You may need to spawn several threads to keep SSD IO queue full, but you may not need even that, since OS prefetcher should keep them full for large enough files.

```rust
buffer.par_chunks_mut(8192).for_each(|chunk| {
            let mut cipher = ChaCha8::new(&key.into(), &nonce.into());
            cipher.seek(0u32);
            cipher.apply_keystream(chunk);
        });```
        is this good? will it take over if a file is huge and if im encrypting files in parallel

**Comment by tarcieri** [comment]
That's using ChaCha20 in an unauthenticated manner, and disclosing unverified plaintexts (which may be attacker-controlled due to [chosen ciphertext attacks](https://en.wikipedia.org/wiki/Chosen-ciphertext_attack)), which is insecure.

You should really use `chacha20poly1305` in conjunction with the [`aead::stream`](https://docs.rs/aead/latest/aead/stream/index.html) module as I mentioned earlier.

**Comment by FU3X** [comment]
> Triple check that your threat model allows unauthenticated encryption.
> 
> > is this good?
> 
> Not quite. I would initialize cipher outside of the closure, pass reference into the closure, clone cipher from the reference, seek the cloned cipher (note that you seek by 0, which has no effect), and finally apply keystream.
> 
> > will it take over if a file is huge and if im encrypting files in parallel
> 
> I doubt it. ChaCha8 can give you ~4 GB/s per core, which is enough to saturate even NVMe SSDs.

i dont care about other people encrypting stuff, i just need the files to be unreversable without the key

**Comment by tarcieri** [comment]
Adaptive chosen ciphertext attacks can recover plaintexts, though they're probably not applicable to your threat model. Still, you should use authenticated encryption.

**Comment by FU3X** [comment]
> Adaptive chosen ciphertext attacks can recover plaintexts, though they're probably not applicable to your threat model. Still, you should use authenticated encryption.

what if the encryption key is kept away for a super long time after 1 encryption, then decrypted for only one set of files

**Comment by FU3X** [comment]
> That's using ChaCha20 in an unauthenticated manner, and disclosing unverified plaintexts (which may be attacker-controlled due to [chosen ciphertext attacks](https://en.wikipedia.org/wiki/Chosen-ciphertext_attack)), which is insecure. See also the [security warning here](https://github.com/RustCrypto/stream-ciphers/tree/master/chacha20#security).
> 
> You should really use `chacha20poly1305` in conjunction with the [`aead::stream`](https://docs.rs/aead/latest/aead/stream/index.html) module as I mentioned earlier.

if i use chacha20 poly, how should i do the nonce? should i derive the nonce from a password or generate a new nonce every chunk and place it in the file

**Comment by tarcieri** [comment]
@FU3X STREAM provides a protocol for the nonce, which is based on a per-segment counter.

The [`StreamPrimitive`](https://docs.rs/aead/latest/aead/stream/trait.StreamPrimitive.html) trait takes care of assembling a nonce prefix and an input counter value into the per-segment nonce.

**Comment by FU3X** [comment]
@tarcieri what am i doing wrong?

```rust
pub fn encrypt_file(filename: &PathBuf, key: &[u8; 32]) -> std::io::Result<()> {
    let mut file = File::open(filename)?;
    if is_file_empty(filename) {
        return Ok(());
    }
    let filename_string = filename.to_string_lossy();
    let output_path = format!("{}.enc", filename_string);

    let mut output_file = File::create(Path::new(&output_path))?;

    let mut nonce = [0u8; 7];
    OsRng.fill_bytes(&mut nonce);

    output_file.write_all(&nonce)?;

    let aead = ChaCha8Poly1305::new(key.as_ref().into());
    let mut stream_encryptor = stream::EncryptorBE32::from_aead(aead, nonce.as_ref().into());

    const BUFFER_LEN: usize = 500 + 16;
    let mut buffer = [0u8; BUFFER_LEN];

    loop {
        let read_count = file.read(&mut buffer)?;

        if read_count == BUFFER_LEN {
            let ciphertext = stream_encryptor
                .encrypt_next(buffer.as_slice())
                .map_err(|err| anyhow!("Encrypting large file: {}", err))
                .unwrap();

            output_file.write_all(&ciphertext)?;
        } else {
            let ciphertext = stream_encryptor
                .encrypt_last(&buffer[..read_count])
                .map_err(|err| anyhow!("Encrypting large file: {}", err))
                .unwrap();
            output_file.write_all(&ciphertext)?;
            break;
        }
    }
    Ok(())
}

pub fn decrypt_file(filename: &PathBuf, key: &[u8; 32]) -> std::io::Result<()> {
    let mut file = File::open(filename)?;
    if is_file_empty(filename) {
        std::fs::remove_file(filename)?;
        return Ok(());
    }
    let filename_string = filename.to_string_lossy();
    let output_path = filename_string.replace(".enc", "");

    let mut output_file = File::create(Path::new(&output_path))?;

    let mut nonce = [0u8; 7];
    OsRng.fill_bytes(&mut nonce);

    output_file.write_all(&nonce)?;

    let aead = ChaCha8Poly1305::new(key.as_ref().into());
    let mut stream_decryptor = stream::DecryptorBE32::from_aead(aead, nonce.as_ref().into());

    const BUFFER_LEN: usize = 500 + 16;
    let mut buffer = [0u8; BUFFER_LEN];

    loop {
        let read_count = file.read(&mut buffer)?;

        if read_count == BUFFER_LEN {
            let ciphertext = stream_decryptor
                .decrypt_next(buffer.as_slice())
                .map_err(|err| anyhow!("Decrypting large file: {}", err))
                .unwrap();

            output_file.write_all(&ciphertext)?;
        } else {
            let ciphertext = stream_decryptor
                .decrypt_last(&buffer[..read_count])
                .map_err(|err| anyhow!("Decrypting large file: {}", err))
                .unwrap();
            output_file.write_all(&ciphertext)?;
            break;
        }
    }
    Ok(())
}```
