### ISSUE TITLE
XSalsa20 implementation missing

### ISSUE THREAD

**Issue by joejacobs** [RustCrypto/stream-ciphers#53]
Hello, I noticed that there isn't an implementation of XSalsa20 in the `salsa20` crate. Is there any particular reason for this? If it's just because no one has gotten around to it yet, I have had a go at implementing this myself (https://github.com/joejacobs/stream-ciphers). Happy to create a PR if you'd like.

**Comment by tarcieri** [comment]
@joejacobs that'd be cool. You can take a look at the XChaCha20 implementation in the `chacha20` crate for reference:

https://github.com/RustCrypto/stream-ciphers/blob/master/chacha20/src/xchacha20.rs

**Comment by joejacobs** [comment]
PRs #54 and #56 have addressed this. Closing the issue.
