### ISSUE TITLE
Why `aes-ctr` crate?

### ISSUE THREAD

**Issue by akhilles** [RustCrypto/stream-ciphers#60]
I may be missing something obvious but why does the `aes-ctr` crate exist? Is there a reason to use `aes_ctr::Aes128Ctr` over `ctr::Ctr128<aes::Aes128>`?

The docs state:
> This crate will select appropriate implementation at compile time depending on target architecture and enabled target features.

but I though that was already handled by the `aes` crate.

**Comment by tarcieri** [comment]
I think the `aes-ctr` crate predates the `aes` crate.

It can probably be retired noting a simple composition of the `aes` and `ctr` crates suffices.
