### ISSUE TITLE
chacha20: avoid panic on counter overflow

### ISSUE THREAD

**Issue by tarcieri** [RustCrypto/stream-ciphers#70]
To avoid repeating the keystream on counter overflow, #68 added an assertion that the counter value is less than `chacha20::MAX_BLOCKS`.

Ideally `SalsaFamilyCipher::block` can be changed to use a fallible API, so instead of panicking it returns an error when the counter overflows.

**Comment by srijs** [comment]
Would it be worth thinking about how to achieve this w/o breaking changes (e.g. add a `try_block` method with a sensible default impl), or do you generally think this warrants a major version bump?

**Comment by tarcieri** [comment]
@srijs I'd like to make some potentially breaking changes anyway. I opened a separate thread about those: https://github.com/RustCrypto/stream-ciphers/issues/71

**Comment by tarcieri** [comment]
I believe this logic should address the issue:

https://github.com/RustCrypto/stream-ciphers/blob/68e3467/chacha20/src/cipher.rs#L182-L188
