### ISSUE TITLE
New crate: RC6

### ISSUE THREAD

**Issue by lqf96** [RustCrypto/stream-ciphers#73]
We can probably add an implementation of the [RC6](https://en.wikipedia.org/wiki/RC6) cipher. Coincidentally their patents expire today (11/28/2019; [source](https://patents.google.com/patent/US5724428), [source](https://patents.google.com/patent/US5835600)).

EDIT: My bad... RC6 is actually block cipher but I think it's nice to have an implementation since no vulnerabilities have been discovered is the past...

**Comment by newpavlov** [comment]
I think we can close this issue as a duplicate of RustCrypto/block-ciphers#1.
