### ISSUE TITLE
sample code

### ISSUE THREAD

**Issue by gzbakku** [RustCrypto/stream-ciphers#74]
hedy can you please provide some sample code as to how to encrypt strings i tried everything thanks mate.

**Comment by tarcieri** [comment]
Is there a specific cipher you're interested in? The ChaCha20 crate has example code:

https://docs.rs/chacha20/0.2.3/chacha20/?search=#usage

...however note unless you have a very specific use case, you should probably be using AEAD ciphers:

https://github.com/rustcrypto/aeads
