### ISSUE TITLE
None of chacha20::ChaCha*Rng implement CryptoRng

### ISSUE THREAD

**Issue by WildCryptoFox** [RustCrypto/stream-ciphers#90]
None of `chacha20::ChaCha*Rng` implement `CryptoRng` despite `rand_chacha::ChaCha*Rng` doing so. Oversight or intended?

@tarcieri 

**Edit**: My motivating use is for a deterministic `impl RngCore + CryptoRng` for tests.

**Comment by WildCryptoFox** [comment]
Thanks @tarcieri

**Comment by tarcieri** [comment]
It was an oversight (the RNG backends were contributed)
